trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: |
    docker build -t kubeconform .
    docker run -v $(pwd)/test-k8s-files:/app kubeconform:latest -d /app
  displayName: 'Docker build & run kubeconform image'


